// Generated by https://quicktype.io

import type { User } from '@/modules/auth/interfaces/user.interface';

export interface Product {
  description: string;
  gender: string;
  id: string;
  images: string[];
  price: number;
  sizes: Size[];
  slug: string;
  stock: number;
  tags: string[];
  title: string;
  user: User;
}

export enum Size {
  L = 'L',
  M = 'M',
  S = 'S',
  XL = 'XL',
  XS = 'XS',
  XXL = 'XXL',
}

export enum Gender {
  KID = 'kid',
  WOMEN = 'women',
  MEN = 'men',
}
